version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: locksmith_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=locksmith_db
    networks:
      - locksmith_network

  locksmith_service:
    build: .
    container_name: locksmith_service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/locksmith_db
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development
      - PORT=3001
    depends_on:
      - mongodb
    networks:
      - locksmith_network

volumes:
  mongodb_data:

networks:
  locksmith_network:
    driver: bridge 